### ISSUE TITLE
Evalutation code seems to not work for the subset re10k dataset

### ISSUE THREAD

**Issue by AnandK27** [dcharatan/pixelsplat#12]
I am running the evaluation code as mentioned in the readme section shown below
`python3 -m src.main +experiment=re10k mode=test dataset/view_sampler=evaluation checkpointing.load=checkpoints/re10k.ckpt`

However, the code exits _without any error_ after showing
```
Test step 000000.
```
and there are no images generated in the `outputs` folder.

Can you let me know what the issue might be? 
Thanks a lot!

**Comment by dcharatan** [comment]
I'm not able to reproduce this issue using the [provided Real Estate 10k subset](https://drive.google.com/drive/folders/1joiezNCyQK2BvWMnfwHJpm2V77c7iYGe) and the command you provided. The images should be written to `outputs/test/re10k`. I recommend using the VS Code debugger with the provided `Test (Debug)` configuration to figure out what's going on. It might be helpful to set breakpoints at `src/main.py:41` (entry point) and `src/model/model_wrapper.py:155` (test step).

Does the program exit for you? What kind of system are you using?

**Comment by AnandK27** [comment]
Thanks, I figured out the issue had to provide proper permissions to save the images in the directory

**Comment by YangBigSir** [comment]
> Thanks, I figured out the issue had to provide proper permissions to save the images in the directory

I have also encountered this exact same problem, how should I solve it? Can you provide a detailed method？Thanks!

**Comment by AnandK27** [comment]
I dont think my solution will help but I changed the volume's read and write permissions before allocating it to my docker container
