### ISSUE TITLE
Training on Custom Dataset

### ISSUE THREAD

**Issue by YoungjuNa-KR** [dcharatan/pixelsplat#17]
First of all, thanks for sharing very interesting work.
I appreciate the effort of the authors.

1) 
I'm trying to apply this method to other datasets (e.g., DTU dataset).
Are there any tips or things to consider before I apply the pixelsplat to the other datasets?

2)
Secondly, is extracting geometry (similar to nerf's volume density thresholding) available in this released version?

Thanks in advance.

**Comment by dcharatan** [comment]
1. The most important thing when implementing a new dataset is to confirm that the camera metadata has been implemented correctly. It's easiest to do this by plotting epipolar lines (see #14). You might also have to configure/change the background color for rendering (see #18). Because we designed pixelSplat around scene-scale datasets, we didn't spend time optimizing performance on object-scale scenes beyond NMR, and so I'm not sure how well pixelSplat would perform on object-scale data out of the box.
2. In principle, any method that's used to extract geometry from regular 3D Gaussian Splatting scenes could be used for scenes produced by pixelSplat. However, we didn't implement geometry extraction for the Gaussians, and I'm not familiar with what people generally do.

**Comment by Warrior456** [comment]
@YoungjuNa-KR I'm sorry to bother you. I'm also going to apply this method to my own data set. But I don't know how to convert the extrinsics camera parameters obtained by colmap calibration into the format required by this repo. For example, the dtu data set provides us with the w2c matrix, I inverse it to get the c2w matrix, and found that it still seems wrong. Have you solved it yet? Looking forward to your reply！

**Comment by dcharatan** [comment]
@Warrior456 Here's some code from a different project I'm working on that converts the camera format used in pixelSplat to and from the COLMAP format. It might be helpful as a starting point. The `read_write_model` import is [this file from the COLMAP repo](https://github.com/colmap/colmap/blob/c0d8926841cf6325eb031c873eaedb95204a1845/scripts/python/read_write_model.py).

```
from pathlib import Path

import numpy as np
import torch
from jaxtyping import Float
from scipy.spatial.transform import Rotation as R
from torch import Tensor

from read_write_model import Camera, Image, read_model, write_model

def read_colmap_model(
    path: Path,
    device: torch.device = torch.device("cpu"),
) -> tuple[
    Float[Tensor, "frame 4 4"],  # extrinsics
    Float[Tensor, "frame 3 3"],  # intrinsics
    list[str],  # image names
]:
    cameras, images, _ = read_model(path)

    all_extrinsics = []
    all_intrinsics = []
    all_image_names = []

    for image in images.values():
        camera: Camera = cameras[image.camera_id]

        # Read the camera intrinsics.
        intrinsics = torch.eye(3, dtype=torch.float32, device=device)
        if camera.model == "SIMPLE_PINHOLE":
            fx, cx, cy = camera.params
            fy = fx
        elif camera.model == "PINHOLE":
            fx, fy, cx, cy = camera.params
        intrinsics[0, 0] = fx
        intrinsics[1, 1] = fy
        intrinsics[0, 2] = cx
        intrinsics[1, 2] = cy
        intrinsics[0] /= camera.width
        intrinsics[1] /= camera.height
        all_intrinsics.append(intrinsics)

        # Read the camera extrinsics.
        qw, qx, qy, qz = image.qvec
        w2c = torch.eye(4, dtype=torch.float32, device=device)
        rotation = R.from_quat([qx, qy, qz, qw]).as_matrix()
        w2c[:3, :3] = torch.tensor(rotation, dtype=torch.float32, device=device)
        w2c[:3, 3] = torch.tensor(image.tvec, dtype=torch.float32, device=device)
        extrinsics = w2c.inverse()
        all_extrinsics.append(extrinsics)

        # Read the image name.
        all_image_names.append(image.name)

    return torch.stack(all_extrinsics), torch.stack(all_intrinsics), all_image_names


def write_colmap_model(
    path: Path,
    extrinsics: Float[Tensor, "frame 4 4"],
    intrinsics: Float[Tensor, "frame 3 3"],
    image_names: list[str],
    image_shape: tuple[int, int],
) -> None:
    h, w = image_shape

    # Define the cameras (intrinsics).
    cameras = {}
    for index, k in enumerate(intrinsics):
        id = index + 1

        # Undo the normalization we apply to the intrinsics.
        k = k.detach().clone()
        k[0] *= w
        k[1] *= h

        # Extract the intrinsics' parameters.
        fx = k[0, 0]
        fy = k[1, 1]
        cx = k[0, 2]
        cy = k[1, 2]

        cameras[id] = Camera(id, "PINHOLE", w, h, (fx, fy, cx, cy))

    # Define the images (extrinsics and names).
    images = {}
    for index, (c2w, name) in enumerate(zip(extrinsics, image_names)):
        id = index + 1

        # Convert the extrinsics to COLMAP's format.
        w2c = c2w.inverse().detach().cpu().numpy()
        qx, qy, qz, qw = R.from_matrix(w2c[:3, :3]).as_quat()
        qvec = np.array((qw, qx, qy, qz))
        tvec = w2c[:3, 3]
        images[id] = Image(id, qvec, tvec, id, name, [], [])

    path.mkdir(exist_ok=True, parents=True)
    write_model(cameras, images, {}, path)

```

**Comment by XLR-man** [comment]
Hi, sorry for my poor knowledge:
for the colmap format dataset, how can i use your code above to transfer in .torch files?
