### ISSUE TITLE
Bug with LPIPS loss

### ISSUE THREAD

**Issue by katjaschwarz** [dcharatan/pixelsplat#19]
Hi David,

thank you for releasing this fantastic code base! 
One small thing I noticed is that when you call the LPIPS loss [here](https://github.com/dcharatan/pixelsplat/blob/main/src/loss/loss_lpips.py#L49), the inputs are in [0,1] but LPIPS actually expects them to be in [-1,1] (see [here](https://github.com/richzhang/PerceptualSimilarity/blob/master/lpips/lpips.py#L113)), or you have to use `self.lpips.forward(..., normalize=True)`.
Could this be the reason that the weight for the loss is so small (0.05) and it is only active after so many iterations?

Best,
Katja

**Comment by dcharatan** [comment]
Thanks for pointing this out! With the fix, it would be interesting to see if it's possible to activate the loss earlier or use a larger weight as you mention. Hopefully, the results will also just get slightly better.

I think it's common to only apply LPIPS later during training. For example, both [Splatter Image](https://github.com/szymanowiczs/splatter-image/blob/00fe5ef7874da71b178a531390aaafa5fa786a72/train_network.py#L228) and [one of our baselines](https://github.com/yilundu/cross_attention_renderer?tab=readme-ov-file#realestate-experiments) do this.
