### ISSUE TITLE
Render a video

### ISSUE THREAD

**Issue by kam1107** [dcharatan/pixelsplat#22]
Hi, this is a great work! I want to render a video but am not familiar with hydra config. Could you please provide a command example (such as for re10k)?

Many thanks!

**Comment by dcharatan** [comment]
The easiest way to generate _any_ video is probably to add `dataset.view_sampler.index_path=assets/evaluation_index_re10k_video.json` to the evaluation command:

```
python3 -m src.main +experiment=re10k mode=test dataset/view_sampler=evaluation checkpointing.load=checkpoints/re10k.ckpt dataset.view_sampler.index_path=assets/evaluation_index_re10k_video.json
```

This will re-render video trajectories from the Real Estate 10k dataset. For custom trajectories, check out the functions that start with `render_video` in `src/model/model_wrapper.py`. These functions are run every so often during training to generate video previews.
