### ISSUE TITLE
Confusion about the e3nn coordniate convention

### ISSUE THREAD

**Issue by SeaBird-Go** [dcharatan/pixelsplat#23]
Hi, thanks for sharing this wonderful work.

I have noticed that you did lots of modifications on the original **diff-gaussian-rasterization** package, to match the e3nn.
![image](https://github.com/dcharatan/pixelsplat/assets/117327481/72856d4d-99bb-44f3-a0ae-f93676141b56)

And from one of the modifications above, you changed the conventions of `x, y, z`. So I am confused about the conventions of the coordinates of the original **diff-gaussian-rasterization** package and the **e3nn** package.

**Comment by dcharatan** [comment]
You can find e3nn's convention on [this page](https://docs.e3nn.org/en/stable/api/o3/o3_sh.html).

> This function match with this table of standard real spherical harmonics from [Wikipedia](https://en.wikipedia.org/wiki/Table_of_spherical_harmonics#Real_spherical_harmonics) when `normalize=True`, `normalization='integral'` and is called with the argument in the order `y,z,x` (instead of `x,y,z`).

I don't think 3D Gaussian Splatting's convention is documented anywhere officially, but you can deduce what it is by looking at the math for the spherical harmonics. Looking at [this diff](https://github.com/dcharatan/diff-gaussian-rasterization-modified/compare/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d...main) (looking at the forward pass is easiest) lets you compare the old and new conventions. The convention changes as follows:

- `y` becomes `x`
- `x` becomes `z`
- `z` becomes `y`

It was easier for me to change the CUDA code to match e3nn's convention, but it's possible there's a way to modify the Wigner D matrices returned by e3nn so they can be used with the original `diff-gaussian-splatting` convention. If you know how to do this, please post about it here!
