### ISSUE TITLE
Is it possible to render a few rays instead of a complete image?

### ISSUE THREAD

**Issue by Pixie8888** [dcharatan/pixelsplat#27]
Hi,

Is it possible to render a few rays (like nerf sampling 2048 rays in each iteration) instead of a complete image?

**Comment by dcharatan** [comment]
No. The Gaussian splatting/rasterization process always operates on full images, not individual rays.

In theory, one could write code to render individual rays, but it would likely be much less efficient (on a per-ray basis) than rendering full images.
