### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by lebron12332** [dcharatan/pixelsplat#29]
I run ```python3 -m src.main +experiment=re10k```, but raises a problem as follows:

AttributeError: Can't pickle local object 'get_data_shim.<locals>.combined_shim'. Did you mean: '_return_value'?

I do not know how to solve it? Can you give me some advice?

**Comment by dcharatan** [comment]
I haven't seen this issue. Can you post your environment (Python version, pip/conda environment, etc.)? That might help narrow down the issue.

**Comment by lebron12332** [comment]
hello, my python version is 3.10.13. Other environment is as follows:
name: pixelsplat
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.12.12=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_0
  - pip=23.3.1=py310h06a4308_0
  - python=3.10.13=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2023d=h04d1e81_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - beartype==0.17.0
      - black==24.1.1
      - cachetools==5.3.2
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - colorspacious==1.1.2
      - contourpy==1.2.0
      - cycler==0.12.1
      - dacite==1.8.1
      - decorator==4.4.2
      - diff-gaussian-rasterization==0.0.0
      - docker-pycreds==0.4.0
      - e3nn==0.5.1
      - einops==0.7.0
      - filelock==3.13.1
      - fire==0.5.0
      - fonttools==4.48.1
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - gitdb==4.0.11
      - gitpython==3.1.41
      - google-auth==2.27.0
      - google-auth-oauthlib==1.2.0
      - grpcio==1.60.1
      - huggingface-hub==0.20.3
      - hydra-core==1.3.2
      - idna==3.6
      - imageio==2.33.1
      - imageio-ffmpeg==0.4.9
      - jaxtyping==0.2.25
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - lightning-lite==1.8.0
      - lightning-utilities==0.3.0
      - lpips==0.1.4
      - markdown==3.5.2
      - markupsafe==2.1.5
      - matplotlib==3.8.2
      - moviepy==1.0.3
      - mpmath==1.3.0
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - networkx==3.2.1
      - numpy==1.26.4
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencv-python==4.9.0.80
      - opt-einsum==3.3.0
      - opt-einsum-fx==0.1.4
      - packaging==23.2
      - pathspec==0.12.1
      - pillow==10.2.0
      - platformdirs==4.2.0
      - plyfile==1.0.3
      - proglog==0.1.10
      - protobuf==4.23.4
      - psutil==5.9.8
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytorch-lightning==1.8.0
      - pyyaml==6.0.1
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - ruff==0.2.1
      - safetensors==0.4.2
      - scikit-image==0.22.0
      - scipy==1.12.0
      - sentry-sdk==1.40.2
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - svg-py==1.4.2
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - tifffile==2024.1.30
      - timm==0.9.12
      - tomli==2.0.1
      - torch==1.13.1+cu116
      - torchaudio==0.13.1+rocm5.2
      - torchmetrics==0.11.4
      - torchvision==0.14.1+cu116
      - tqdm==4.66.1
      - typeguard==2.13.3
      - typing-extensions==4.9.0
      - urllib3==2.2.0
      - wandb==0.16.3
      - werkzeug==3.0.1
      - yarl==1.9.4

**Comment by lebron12332** [comment]
solved! update pytorch-lightning from 1.8.0 to 2.2.0. Thanks for your help.
