### ISSUE TITLE
gaussian scale coordinate

### ISSUE THREAD

**Issue by wangjksjtu** [dcharatan/pixelsplat#31]
Thanks so much for the fantastic work!! @dcharatan 

Could you please elaborate more on the note here when constructing Gaussians?
```
        return Gaussians(
            means=means,
            covariances=covariances,
            harmonics=rotate_sh(sh, c2w_rotations[..., None, :, :]),
            opacities=opacities,
            # Note: These aren't yet rotated into world space, but they're only used for
            # exporting Gaussians to ply files. This needs to be fixed...
            scales=scales,
            rotations=rotations.broadcast_to((*scales.shape[:-1], 4)),
        )
```

Looking forward to your reply!

**Comment by dcharatan** [comment]
I posted a few comments about this in issue #9. Take a look there and feel free to post a follow-up if you still have questions!

**Comment by dcharatan** [comment]
Another thing I just noticed: that comment refers to the rotations, not the scales, so it should be one line lower! Sorry if that's what was confusing! The scales themselves don't have to be rotated.
