### ISSUE TITLE
Bug in view_sampler_bounded regarding maximum gap between context views

### ISSUE THREAD

**Issue by Chrixtar** [dcharatan/pixelsplat#34]
Hello David,

thank you for this awesome codebase.
If I am not mistaken, there is a small bug in the bounded view sampler for the computation of the maximum gap between context views [here](https://github.com/dcharatan/pixelsplat/blob/9b4375320e30ab2a18c614b0bed96f32c9cbb77d/src/dataset/view_sampler/view_sampler_bounded.py#L61).
I think this should be `max_gap = min(num_views - 1, max_gap)`.
This should also influence the experiments on re10k in the sense that `max_distance_between_context_views` [here](https://github.com/dcharatan/pixelsplat/blob/9b4375320e30ab2a18c614b0bed96f32c9cbb77d/config/dataset/view_sampler_dataset_specific_config/bounded_re10k.yaml#L6) is effectively 45 instead of 192 and `initial_max_distance_between_context_views` [here](https://github.com/dcharatan/pixelsplat/blob/9b4375320e30ab2a18c614b0bed96f32c9cbb77d/config/dataset/view_sampler_dataset_specific_config/bounded_re10k.yaml#L10) 25 instead of 45.

Please correct me, if I am wrong.

Best regards
Chris

**Comment by dcharatan** [comment]
This indeed looks like a bug! Thank you for finding this. I've updated the code to fix the bug and changed the experiment configurations to mimic the original unintended behavior, so training should still produce the same results that were shown in the paper.

Note that the frame indices used for evaluation were generated using the code in `src/evaluation/evaluation_index_generator.py`, which doesn't have this bug, so the context views used for evaluation (the ones in the `assets` folder) are generally more than 45 frames apart.
