### ISSUE TITLE
Selection of source Views and target View

### ISSUE THREAD

**Issue by skrya** [dcharatan/pixelsplat#36]
Thanks or the amazing work! My question is regarding the source views and target views used for training and inference. Does the camera trajectory of the scene is assumed to be source view 1 -> target view -> source view 2 (more of an interpolation of two source images). Can the model work for the case of a camera trajectory source view 1 -> source view 2 -> target view (extrapolation), where model needs to also generate new information not present in source view 1 and source view 2? How is the training and inference conducted w.r.t above to cases?

**Comment by dcharatan** [comment]
The views are assumed to be `source view 1 -> target view -> source view 2`. pixelSplat doesn't have a mechanism to hallucinate content that's not observed by at least one source view. In other words, `source view 1 -> source view 2 -> target view` might work if the target view mostly contains content that's visible in the source views, but isn't expected to work in general. However, adding a generative component to pixelSplat would be an interesting future direction!
