### ISSUE TITLE
Problem testing acid dataset

### ISSUE THREAD

**Issue by blue-531** [dcharatan/pixelsplat#38]
Thank you for great work!
Now I have problem testing on acid dataset, although I downloaded full test set of acid datasest it didn't work. (same as #28 )
I think view_sampler for re10k dataset doesn't work for acid dataset. Please let me know if we need different config setting for acid dataset.

**Comment by dcharatan** [comment]
To evaluate on ACID, you have to specify the ACID evaluation index (otherwise, the code will try to load the scene IDs from Real Estate 10k, which don't exist in ACID):

```
python3 -m src.main +experiment=acid mode=test dataset/view_sampler=evaluation dataset.view_sampler.index_path=assets/evaluation_index_acid.json checkpointing.load=checkpoints/acid.ckpt
```

I've updated the README to reflect this. Sorry for not specifying this earlier!
