### ISSUE TITLE
Could you release the dataset of re10k of generate_point_cloud_figure？

### ISSUE THREAD

**Issue by zhongqiu1245** [dcharatan/pixelsplat#39]
Thank you for your amazing job
Could you release the dataset of re10k of `generate_point_cloud_figure.py`？ (2c52d9d606a3ece2, 71a1121f817eb913, d70fc3bef87bffc1, f0feab036acd7195, a93d9d0fd69071aa, which are not in sub_re10k)
Thank you!

**Comment by dcharatan** [comment]
I've compiled a subset of the dataset that includes all of the scenes referenced in `generate_point_cloud_figure.py`. You can find it with the rest of the datasets [here](https://drive.google.com/drive/folders/1joiezNCyQK2BvWMnfwHJpm2V77c7iYGe?usp=drive_link). As a reminder, feel free to send us an email if you want the full processed dataset!
