### ISSUE TITLE
Implementing on my own datasets

### ISSUE THREAD

**Issue by LaFeuilleMorte** [dcharatan/pixelsplat#4]
Hi, I' m so exciting about your brilliant work. Is there any instructions on implementing this work on our own datasets. (Like iamges with camera extrinsics or colmap format datasets).

**Comment by dcharatan** [comment]
If you're implementing your own dataset, the most important thing is getting the formats for the intrinsics and extrinsics right. See the note [here](https://github.com/dcharatan/pixelsplat?tab=readme-ov-file#camera-conventions) for more details. Other than that, it's just a matter of returning the correct keys (there's an example [here](https://github.com/dcharatan/pixelsplat/blob/a0050e1e052bb0eb5dab06c2bbd6be2c4bfc6225/src/dataset/dataset_re10k.py#L153-L171) and a specification in `src/dataset/types.py`).

To make sure that the camera metadata has been converted correctly, it can be helpful to plot the epipolar lines between the context views. They should look something like this, where the 3D location under each point on the left is somewhere under the corresponding epipolar line on the right.

![image](https://github.com/dcharatan/pixelsplat/assets/13124225/416ad316-b634-456a-a63f-c87f16c3937a)

I can post an example of how to plot these epipolar lines with the existing code if you think it would be helpful.

**Comment by yousefh409** [comment]
@LaFeuilleMorte Were you able to get the model working on your own dataset? If so, could you share the steps you took to do so? It would be greatly appreciated!
