### ISSUE TITLE
Evaluation Metric Command

### ISSUE THREAD

**Issue by jk4011** [dcharatan/pixelsplat#42]
Thank you for your excellent work! 
Your method creates amazing novel views from just two images. 

I'd like to replicate the evaluation metrics, like PSNR, mentioned in your paper. 
However, the command in the README only generates test images. 
Could you provide the command for calculating these metrics in your code?

**Comment by dcharatan** [comment]
To compute evaluation metrics, you can use `src.scripts.compute_metrics`:

```
python3 -m src.scripts.compute_metrics +experiment=re10k +evaluation=re10k
python3 -m src.scripts.compute_metrics +experiment=acid +evaluation=acid
```

You can also use this script to create side-by-side videos if you do `+evaluation=re10k_video` instead, for example.
