### ISSUE TITLE
Same CUDA OOM problem with pytorch1.8.0 + cu11.1 on RTX A6000

### ISSUE THREAD

**Issue by railgun526** [dcharatan/pixelsplat#45]
Hi @kevinYitshak , I still encounter the same error following the link. My environment is pytorch1.8.0 + cu11.1 on RTX 3090Ti.

_Originally posted by @Pixie8888 in https://github.com/dcharatan/pixelsplat/issues/8#issuecomment-1937408010_

**Comment by railgun526** [comment]
File "/home/miniconda3/envs/gs18_copy/lib/python3.8/site-packages/diff_gaussian_rasterization/__init__.py", line 92, in forward
    num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args)
RuntimeError: CUDA out of memory. Tried to allocate 87964.63 GiB (GPU 0; 44.56 GiB total capacity; 1.60 GiB already allocated; 41.18 GiB free; 1.66 GiB reserved in total by PyTorch)
Hi @dcharatan I encountered OOM when doing the forward process in pixelsplat. However, with the same environment, it works well in original gaussian splatting. Could you please help me for this problem?

**Comment by dcharatan** [comment]
I'm still not sure what causes this issue. I would recommend trying out the environments that work for other people in #8. As far as I can tell, there's no reason why our modifications to `diff-gaussian-rasterization` should cause this issue. It might be worth trying to include our modified `diff-gaussian-rasterization` as a submodule and then doing `pip install .` (like in the original Gaussian Splatting repo) in case the build process this invokes is somehow different than what doing `pip install git+<link>` uses.
