### ISSUE TITLE
Problem in rendering

### ISSUE THREAD

**Issue by Pixie8888** [dcharatan/pixelsplat#46]
Dear author,

I am using pixelsplat on my own datset. But the result is very bad, like this below. I don't know what caused the pattern of lower left and right. Also, why there are so many black dots? I set background color to black, and I checked the image value is within 0~255.
 Do you have any suggestions for debugging? Thank you very much!

![image](https://github.com/dcharatan/pixelsplat/assets/72333326/c9142cfe-a81f-4dfd-bb91-c26d7980a600)

**Comment by dcharatan** [comment]
The input image range should be 0 to 1 (float). Because of the artifacts in the bottom of the scene, I think this could be a problem with the input data format. What's the dataset you're using? And are you trying to train on the dataset or evaluate a pre-trained checkpoint on new data?

**Comment by dcharatan** [comment]
Some more things to try:

- Double-check that the intrinsics and extrinsics are correct by visualizing the epipolar lines as described [here](https://github.com/dcharatan/pixelsplat/issues/17#issuecomment-1896261190).
- Confirm that the context views have enough visual overlap to make learning feasible.
- Overfit on a few scenes that seem like they should work (see #40).
- Try out different near/far disparity thresholds and visualize the resulting spatial distribution of the buckets (it's easier for the network to learn when more of the buckets are overlapping)

I might be able to come up with some more ideas if there are more details you can provide. I haven't seen the artifacts/black dots while training on RE10k and ACID though, so I'm not sure what causes those. Good luck!

**Comment by CBoLee** [comment]
> Dear author, I found the main reason is that I mistakenly set the opacity to be always 1 and downsampled the src image to be smaller than target image that causes these artifacts. Thank you very much for your kind help!
Hello, I'm wondering how to prepare the ScanNet dataset for use. For example, how do I convert it into a .torch file, or what method did you use to get it working with the PixelSplat algorithm?

**Comment by CBoLee** [comment]
> Dear author, I found the main reason is that I mistakenly set the opacity to be always 1 and downsampled the src image to be smaller than target image that causes these artifacts. Thank you very much for your kind help!

Hello, I'm wondering how to prepare the ScanNet dataset for use. For example, how do I convert it into a .torch file, or what method did you use to get it working with the PixelSplat algorithm?

**Comment by CBoLee** [comment]
> Dear author,
> 
> I am using pixelsplat on my own datset. But the result is very bad, like this below. I don't know what caused the pattern of lower left and right. Also, why there are so many black dots? I set background color to black, and I checked the image value is within 0~255. Do you have any suggestions for debugging? Thank you very much!
> 
> ![image](https://private-user-images.githubusercontent.com/72333326/309191513-c9142cfe-a81f-4dfd-bb91-c26d7980a600.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTY0NTEsIm5iZiI6MTcyODM5NjE1MSwicGF0aCI6Ii83MjMzMzMyNi8zMDkxOTE1MTMtYzkxNDJjZmUtYTgxZi00ZGZkLWJiOTEtYzI2ZDc5ODBhNjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE0MDIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxOThhZWYxNDI2YTA2YjBkM2FlN2E2ZjliM2NkNDE0ZWEzNDFjNjAwZDRiNTJiMzE2ZGMyOWJlMzk0MjM2ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3aMkokEraT5CCK-7gRztxQR_n1EKgTIF78CyhdFJ-pQ)

Hello, I'm wondering how to prepare the ScanNet dataset for use. For example, how do I convert it into a .torch file, or what method did you use to get it working with the PixelSplat algorithm?

**Comment by XLR-man** [comment]
> > Dear author,
> > I am using pixelsplat on my own datset. But the result is very bad, like this below. I don't know what caused the pattern of lower left and right. Also, why there are so many black dots? I set background color to black, and I checked the image value is within 0~255. Do you have any suggestions for debugging? Thank you very much!
> > ![image](https://private-user-images.githubusercontent.com/72333326/309191513-c9142cfe-a81f-4dfd-bb91-c26d7980a600.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTY0NTEsIm5iZiI6MTcyODM5NjE1MSwicGF0aCI6Ii83MjMzMzMyNi8zMDkxOTE1MTMtYzkxNDJjZmUtYTgxZi00ZGZkLWJiOTEtYzI2ZDc5ODBhNjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE0MDIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxOThhZWYxNDI2YTA2YjBkM2FlN2E2ZjliM2NkNDE0ZWEzNDFjNjAwZDRiNTJiMzE2ZGMyOWJlMzk0MjM2ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3aMkokEraT5CCK-7gRztxQR_n1EKgTIF78CyhdFJ-pQ)
> 
> Hello, I'm wondering how to prepare the ScanNet dataset for use. For example, how do I convert it into a .torch file, or what method did you use to get it working with the PixelSplat algorithm?

Hey, i have same issues, did you solve it?
