### ISSUE TITLE
Can this work be trained on different datasets?

### ISSUE THREAD

**Issue by chenwydj** [dcharatan/pixelsplat#47]
Dear authors,

Thanks for the great work and congratulations on the CVPR acceptance!

May I ask if this work can be trained on different datasets, say Objaverse or Google Scanned Objects?

Thank you very much!

**Comment by dcharatan** [comment]
It should be possible to train on other datasets as long as they provide ground-truth camera poses. See issues #4, #14, #17, #20, #25, #30, #33, #36, and #46, which all have details that might be helpful when using a new dataset.
