### ISSUE TITLE
Confusion about spherical harmonic coefficients

### ISSUE THREAD

**Issue by caiyongqi** [dcharatan/pixelsplat#51]
Is the following code transforming the predicted SH coefficients in the camera coordinate system to the world coordinate system?

https://github.com/dcharatan/pixelsplat/blob/f4ae9c1396ce62097b407e819321f5819d7788a9/src/model/encoder/common/gaussian_adapter.py#L90

In addition, the "diff-gaussian-rasterization-modified" only modifies the content related to the SH coefficient and has no effect on other parameters(scale, rotate...)?

**Comment by dcharatan** [comment]
Yes, it's transforming the SH coefficients from the camera coordinate system to the world coordinate system. The `diff-gaussian-rasterization-modifed` code changes the convention for the spherical harmonics to match the e3nn library's conventions. This makes it possible to use the Wigner D matrices provided by e3nn to rotate the spherical harmonics. For more details, see [this comment](https://github.com/graphdeco-inria/gaussian-splatting/issues/176#issuecomment-1918708917).
