### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by YZWYD** [dcharatan/pixelsplat#52]
Hello author, could you please advise me on how to utilize the pre-trained weights you shared to process a pair of images and generate the corresponding 3D model?

**Comment by ArisWayne** [comment]
same question

**Comment by YZWYD** [comment]
So can you use the&nbsp;Pre-trained Models now? I cannot see your reply on github.


Z&amp;Y
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dcharatan/pixelsplat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月6日(星期三) 凌晨3:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dcharatan/pixelsplat] How to use it? (Issue #52)





 
same question

**Comment by dcharatan** [comment]
See [this part of the README](https://github.com/dcharatan/pixelsplat/tree/main?tab=readme-ov-file#evaluation) for instructions on how to run evaluation/inference. If you want 3D models in `.ply` format, you can check out `src/paper/generate_point_cloud_figure.py`. It uses the `export_ply` function from `src/model/ply_export.py` to export the output (3D Gaussians) of the encoder.
