### ISSUE TITLE
How to generate point cloud in world coordinate?

### ISSUE THREAD

**Issue by railgun526** [dcharatan/pixelsplat#55]
Hi @dcharatan, thank you for helping me solving so many questions! I have a small question to ask. I want to generate point cloud in world coordinate in 3D space and use open3d to visualize it. I found that you have written generate_point_cloud_figure.py but it generate point cloud which is projected to 2D plane. I am wondering if the means of the gaussian can represent the point cloud?  By simply doing so, I got the result which may not seem satisfactory...
![微信图片_20240307001440](https://github.com/dcharatan/pixelsplat/assets/134762680/1f58beab-7af0-4d19-8800-f1ae80997916)
Could you please give me some clues about how to convert gaussians into point cloud in world coordinate in 3D space? Thanks a lot!

**Comment by dcharatan** [comment]
See #43 -- in practice, it can be helpful to filter out far-away Gaussians, since the model tends to create a lot of junk points behind the correct, 3D-consistent scene.
