### ISSUE TITLE
Adjust camera intrinsics when resizing and cropping

### ISSUE THREAD

**Issue by Trainingzy** [dcharatan/pixelsplat#58]
Hi, thanks a lot for your great work!

I have a question regarding the camera intrinsics. In your [implementation of center crop](https://github.com/dcharatan/pixelsplat/blob/1947b629da93b7327cb6d7a4901e77500a566231/src/dataset/shims/crop_shim.py#L45), focal length is adjusted. I think focal length should be same when center crop while only adjusted when resizing. As the focal length is normalized, it should not be changed when resizing and center cropping.

If I understand it correctly, when center crop to square, the bugs are introduced here.

**Comment by dcharatan** [comment]
When center-cropping _unnormalized_ intrinsics, you're right that the principal point should change, but the focal length shouldn't. Unnormalized intrinsics look like this:

```
[[fx,  0, cx],
 [ 0, fy, cy],
 [ 0,  0,  1]]
```
However, our intrinsics are normalized as follows:

```
[[fx / w,      0, cx / w],
 [     0, fy / h, cy / h],
 [     0,      0,      1]]
```

Once you apply the normalization, the math counter-intuitively makes the focal length change for center-cropping while the principal point stays the same. For example, the new top-left value (corresponding to fx) becomes `(fx / old_w) * old_w / new_w`, and the top-right value (corresponding to cx) becomes `(cx / old_w) * old_w * (new_w / old_w) / new_w = cx / old_w`, assuming that `cx` and `cy` are 0.5.

**Comment by Trainingzy** [comment]
Okay. Thanks a lot for answering!

**Comment by FudongGe** [comment]
Hi, if only resizing without cropping, is it necessary to adjust the internal parameters (already been normalized)?

**Comment by FudongGe** [comment]
Hi, if only resizing without cropping, is it necessary to adjust the intrinsics (already been normalized)? In other words, what should be the intrinsics adjustments for center crop and resize, respectively (if intrinsics have been normalized)？

**Comment by FudongGe** [comment]
Hi, if only resizing without cropping, is it necessary to adjust the intrinsics (already been normalized)? In other words, what should be the intrinsics adjustments for center crop and resize, respectively (if intrinsics have been normalized)？

Specifically, why is there no scaling of intrinsics in the rescale function？
![image](https://github.com/user-attachments/assets/365e79e0-051c-4514-8403-474233b90114)
