### ISSUE TITLE
Could you share your processed full data?

### ISSUE THREAD

**Issue by thucz** [dcharatan/pixelsplat#6]
Hi! Since your process script needs the full dataset, now I cannot get so much disk storage. Could you share your processed data(RealEstate10k, 500GB and ACID 160GB)?

**Comment by dcharatan** [comment]
Please send a note to `charatan@mit.edu` to get the datasets!

**Comment by thucz** [comment]
Hi! I sent you an email two days ago. have you received that email? Looking forward to your processed data.
