### ISSUE TITLE
Questions about adjusting camera intrinsics in data augmentation

### ISSUE THREAD

**Issue by zxp46** [dcharatan/pixelsplat#60]
Thanks for the implementation of your awesome work.

I have a question about why the camera intrinsics of center crop is designed in this way.
In your code, I think you only adjusted the focal length according to the size change by cropping, but why not consider the change in principal points and the scaling factor by rescale?

**Comment by dcharatan** [comment]
See #58. Also note that the Gaussian Splatting rasterizer only supports principal points at image centers.
