### ISSUE TITLE
Question about the content of the  .torch file 

### ISSUE THREAD

**Issue by SuzyZhao0417** [dcharatan/pixelsplat#61]
Thans for your work！I check the content in .torch file, and the attributes  in 'cameras' has 18 parameters，what does each parameter represent (as the first two items should represent the dimensions of the image)？

**Comment by dcharatan** [comment]
You can see how they're used here:
https://github.com/dcharatan/pixelsplat/blob/1947b629da93b7327cb6d7a4901e77500a566231/src/dataset/dataset_re10k.py#L175-L198
