### ISSUE TITLE
Hello, I want to use the ply_export.py file provided in your code to directly generate a .ply point cloud file. However, the scales and rotation parameters in your code are expressed as covariance. How can I convert the covariance into scales and rotation and then output the ply file?

### ISSUE THREAD

**Issue by wdlllllllll** [dcharatan/pixelsplat#63]
Hello, I want to use the ply_export.py file provided in your code to directly generate a .ply point cloud file. However, the scales and rotation parameters in your code are expressed as covariance. How can I convert the covariance into scales and rotation and then output the ply file?

**Comment by wdlllllllll** [comment]
解决了哈

**Comment by johnren-code** [comment]
大佬，我想问一下你导出的点云有颜色吗？为什么我导出的点云没有颜色

**Comment by wdlllllllll** [comment]
> 大佬，我想问一下你导出的点云有颜色吗？为什么我导出的点云没有颜色

有颜色啊

**Comment by wdlllllllll** [comment]
我是直接在gaussian_adapter里面调用的ply_export.py

> 大佬你是直接使用的原本的代码没有修改吗，那可能是我这边球谐系数的问题

**Comment by johnren-code** [comment]
好的好的，谢谢大佬

**Comment by FudongGe** [comment]
@chenkangjie1123 @johnren-code 两位大佬请问是如何可视化的呢？我尝试了使用生成的.ply文件进行可视化，但是感觉结果很奇怪，而且也不显示颜色
![image](https://github.com/user-attachments/assets/f1b5b785-6500-4cd7-a9cb-fd2d9759cb58)
