### ISSUE TITLE
Missing of re10k/train/index.json

### ISSUE THREAD

**Issue by zhangshengjun2019** [dcharatan/pixelsplat#69]
I unzip the complete dataset of re10k. But I did not find re10k/train/index.json. I wonder how can I get this file.

**Comment by dcharatan** [comment]
For anyone who runs into this issue, please try `unzip -l re10k.zip`. If you don't see the following...

```
   262296  2023-10-23 12:45   re10k/test/index.json
  2377188  2023-10-23 12:56   re10k/train/index.json
```

...please post a comment!
