### ISSUE TITLE
An error ocurred

### ISSUE THREAD

**Issue by Yuhuoo** [dcharatan/pixelsplat#72]
when I run the command "python3 -m src.main +experiment=re10k data_loader.train.batch_size=1", I have meet the error as follows:

(venv) (base) xxx@test-X640-G40:~/code/pixelsplat$ python3 -m src.main +experiment=re10k data_loader.train.batch_size=1
Saving outputs to /data1/GaoAo/code/pixelsplat/outputs/2024-05-11/13-57-01.
rm: cannot remove 'outputs/local': No such file or directory

Error executing job with overrides: ['+experiment=re10k', 'data_loader.train.batch_size=1']

----------------------------------------------------------------------------------------------------------------------------------
<frozen runpy> 198 _run_module_as_main

<frozen runpy> 88 _run_code

main.py 142 <module>
train()

main.py 94 decorated_main
_run_hydra(

utils.py 394 _run_hydra
_run_app(

utils.py 457 _run_app
run_and_report(

utils.py 223 run_and_report
raise ex

utils.py 220 run_and_report
return func()

utils.py 458 <lambda>
lambda: hydra.run(

hydra.py 132 run
_ = ret.return_value

utils.py 260 return_value
raise self._return_value

utils.py 186 run_job
ret.return_value = task_function(task_cfg)

main.py 92 train
trainer = Trainer(

argparse.py 70 insert_env_defaults
return fn(self, **kwargs)

trainer.py 401 __init__
self._accelerator_connector = _AcceleratorConnector(

accelerator_connector.py 166 __init__
self._lazy_init_strategy()

accelerator_connector.py 610 _lazy_init_strategy
self.strategy.set_world_ranks()

ddp.py 210 set_world_ranks
self.cluster_environment.set_global_rank(self.node_rank * self.num_processes + self.local_rank)

parallel.py 62 node_rank
return self.cluster_environment.node_rank() if self.cluster_environment is not None else 0

slurm.py 155 node_rank
return int(os.environ["SLURM_NODEID"])

<frozen os> 679 __getitem__

KeyError:
SLURM_NODEID

**Comment by dcharatan** [comment]
This should go away if you remove the following line:

https://github.com/dcharatan/pixelsplat/blob/e4d34e8c7827525b3fe71b8bb94f1618f70080e7/src/main.py#L104
