### ISSUE TITLE
RuntimeError: GET was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by renaissanceee** [dcharatan/pixelsplat#76]
i install torch='2.1.0+cu121', but get error when loading re10k.ckpt.

**Comment by dcharatan** [comment]
I suspect this is a problem with your CUDA/PyTorch installation, not with the pixelSplat code. Are you able to load other model checkpoints using your environment?

**Comment by renaissanceee** [comment]
> I suspect this is a problem with your CUDA/PyTorch installation, not with the pixelSplat code. Are you able to load other model checkpoints using your environment?

thanks for your reply, the same for re10k and acid, because the error happens in torch.nn.conv2d inside Resnet backbone. But I checked the torch version and nvcc-V.
