### ISSUE TITLE
Depth Estimation for epipolar transformation

### ISSUE THREAD

**Issue by Eyvaz27** [dcharatan/pixelsplat#77]
Hello, I have observed that when we are increasing the resolution of the images and count of images, time requirements increase almost exponentially due to intersect_rays function in src.geometry.projection.py.  Would it be useful to use something like https://math.stackexchange.com/questions/1993953/closest-points-between-two-lines/4764188#4764188
to get direct depth estimates

**Comment by dcharatan** [comment]
Have you profiled the code to make sure that `intersect_rays` is actually what's causing a substantial slowdown? If you find that the approach from Stack Exchange is much faster, I would be happy to accept a pull request!
