### ISSUE TITLE
Only a part of scenes are evaluated?

### ISSUE THREAD

**Issue by thucz** [dcharatan/pixelsplat#79]
<img width="1772" alt="image" src="https://github.com/dcharatan/pixelsplat/assets/135981918/05a1ce8b-766f-4968-9be8-b59115b09268">

Some scenes seem to be skipped because of the small frame number.

Is the total number of evaluated scenes on RE10K 6474 for you too?

**Comment by dcharatan** [comment]
I don't remember the exact number, but that sounds right. Some of the scenes don't have enough frames for us to evaluate on them.

**Comment by thucz** [comment]
Thanks!
