### ISSUE TITLE
How to custom the code for multiple dataset with different sampler parameters?

### ISSUE THREAD

**Issue by thucz** [dcharatan/pixelsplat#80]
I have two new datasets with RGB-D ground truth. But their camera movement speeds are different. I want to set different `max_context_gap` for each dataset.  Do you know how to change your code and configuration for my purpose?

**Comment by dcharatan** [comment]
The easiest way would probably be to do some subsampling within the dataset (before the sampler is called), such that the movement speeds roughly line up.
