### ISSUE TITLE
RealEstate10k numerical evaluation

### ISSUE THREAD

**Issue by VitorGuizilini-TRI** [dcharatan/pixelsplat#84]
Hi, congratulations on the great work!
Can you please provide more information regarding the numerical evaluation? I.e., how each test scene was sampled, what's the stride, and so forth.  Thank you!

**Comment by dcharatan** [comment]
The test scenes and strides are specified in "evaluation index" files, which are included in the [assets folder](https://github.com/dcharatan/pixelsplat/tree/main/assets). These evaluation indices were created with [this script](https://github.com/dcharatan/pixelsplat/blob/main/src/scripts/generate_evaluation_index.py). If you want to compare against pixelSplat using the exact evaluation that's in the tables in the paper, have your model output the set of images described in the evaluation index, then run [this script](https://github.com/dcharatan/pixelsplat/blob/main/src/scripts/compute_metrics.py) to compute the metrics. In case you're interested, the scripts used to generate stuff in the paper (tables, figures, etc.) are [here](https://github.com/dcharatan/pixelsplat/tree/main/src/paper).
