### ISSUE TITLE
How to apply the pixelsplat on my own dataset?

### ISSUE THREAD

**Issue by liustu** [dcharatan/pixelsplat#86]
Hi, would there are some command about how to process my own data for pixelsplat?

**Comment by dcharatan** [comment]
The easiest way to do so would be to create `.torch` files like the ones used for the Real Estate 10k and ACID datasets. There's no official guide/script, but the format should be self-explanatory. Just make sure you're saving the camera metadata correctly as described [here](https://github.com/dcharatan/pixelsplat?tab=readme-ov-file#camera-conventions). I'm happy to answer questions if you run into any issues!
