### ISSUE TITLE
Question about code

### ISSUE THREAD

**Issue by Gynjn** [dcharatan/pixelsplat#88]
Thanks for sharing your great work.

BTW, I have some questions about the code.

1. https://github.com/dcharatan/pixelsplat/blob/5d5735eaeea59b67eb9527192bcde3aa20da0342/src/dataset/shims/augmentation_shim.py#L13    In this line, the meaning of this code is `reflect.inverse() @ extrinsics @ reflect` ?
2. Also, w.r.t w2c not c2w it can be applied with the same convention in extrinsics? I mean `reflect.inverse() @ w2c @ reflect` means the reflection of w2c matrix.

Thanks in advance.

**Comment by dcharatan** [comment]
The `reflect` matrix is involutory (i.e. `reflect.inverse() == reflect`). As a result, `reflect @ w2c @ reflect` is the same as `(reflect @ c2w @ reflect).inverse()`, and `reflect.inverse() @ extrinsics @ reflect` is the same as `reflect @ extrinsics @ reflect`.
