### ISSUE TITLE
Re10k_subset numerical evaluation

### ISSUE THREAD

**Issue by Gaozihui** [dcharatan/pixelsplat#89]
Hi, congratulations on your work!

I got results of re10k_subset in outputs/test and when I run
`python3 -m src.scripts.compute_metrics +experiment=re10k +evaluation=re10k dataset.roots=[datasets/re10k_subset]`
it outputs skipping and without a numerical eval:
Testing: |                                                                                                                                | 0/? [00:00<?, ?it/s]Skipping "5aca87f95a9412c6".
Skipping "322261824c4a3003".
Testing DataLoader 0:   0%|                                                                                                              | 0/41 [00:00<?, ?it/s]Skipping "5aca87f95a9412c6".
Testing DataLoader 0:   2%|██▍                                                                                                 | 1/41 [00:00<00:00, 1084.64it/s]Skipping "322261824c4a3003".
Testing DataLoader 0:   5%|████▉                                                                                                | 2/41 [00:00<00:00, 475.19it/s]Skipping "17d9303ee77c3a3d".
Testing DataLoader 0:   7%|███████▍                                                                                             | 3/41 [00:00<00:00, 377.63it/s]Skipping "17d9303ee77c3a3d".
Skipping "bc95e5c7e357f1b7".
Skipping "f7c0fa5b81552d35".
Skipping "ffa95c3b40609c76".
Skipping "bc95e5c7e357f1b7".
Testing DataLoader 0:  10%|█████████▉                                                                                            | 4/41 [00:00<00:00, 50.82it/s]Skipping "f7c0fa5b81552d35".
Testing DataLoader 0:  12%|████████████▍                                                                                         | 5/41 [00:00<00:00, 60.90it/s]Skipping "ffa95c3b40609c76".
Testing DataLoader 0:  15%|██████████████▉                                                                                       | 6/41 [00:00<00:00, 70.36it/s]

**Comment by Gaozihui** [comment]
Also, I run `python3 -m src.scripts.generate_evaluation_index +experiment=re10k +evaluation=re10k dataset.roots=[datasets/re10k_subset]` to generate re10k_subset index but I have no idea how to use it.

**Comment by dcharatan** [comment]
For evaluation, you'll need the full dataset (see the note in the README—email us to obtain it).

You would only need to generate a new evaluation index if you're running pixelSplat on your own dataset. In that case, it's used with [this](https://github.com/dcharatan/pixelsplat/blob/dea327d24820b59c5293677fc1f5e6557617430d/src/dataset/view_sampler/view_sampler_evaluation.py#L22) configuration item. You can change the view sampler/this configuration from the command line. For example, here's the ACID setup from the README:

```
python3 -m src.main +experiment=acid mode=test dataset/view_sampler=evaluation dataset.view_sampler.index_path=assets/evaluation_index_acid.json checkpointing.load=checkpoints/acid.ckpt
```

**Comment by CBoLee** [comment]
> For evaluation, you'll need the full dataset (see the note in the README—email us to obtain it).
> 
> You would only need to generate a new evaluation index if you're running pixelSplat on your own dataset. In that case, it's used with [this](https://github.com/dcharatan/pixelsplat/blob/dea327d24820b59c5293677fc1f5e6557617430d/src/dataset/view_sampler/view_sampler_evaluation.py#L22) configuration item. You can change the view sampler/this configuration from the command line. For example, here's the ACID setup from the README:
> 
> ```
> python3 -m src.main +experiment=acid mode=test dataset/view_sampler=evaluation dataset.view_sampler.index_path=assets/evaluation_index_acid.json checkpointing.load=checkpoints/acid.ckpt
> ```

hello

> For evaluation, you'll need the full dataset (see the note in the README—email us to obtain it).
> 
> You would only need to generate a new evaluation index if you're running pixelSplat on your own dataset. In that case, it's used with [this](https://github.com/dcharatan/pixelsplat/blob/dea327d24820b59c5293677fc1f5e6557617430d/src/dataset/view_sampler/view_sampler_evaluation.py#L22) configuration item. You can change the view sampler/this configuration from the command line. For example, here's the ACID setup from the README:
> 
> ```
> python3 -m src.main +experiment=acid mode=test dataset/view_sampler=evaluation dataset.view_sampler.index_path=assets/evaluation_index_acid.json checkpointing.load=checkpoints/acid.ckpt
> ```

hello，thank your excellent work，I'm interested in accessing the complete RealEstate10K dataset for my research. Could you please provide access details?my Email is licypress0102@gmail.com
