### ISSUE TITLE
How to visualize the 3D gaussians as shown in your paper?

### ISSUE THREAD

**Issue by thucz** [dcharatan/pixelsplat#9]
Hi! Could you tell me how to visualize the 3D gaussians?

**Comment by dcharatan** [comment]
The figures showing the Gaussian "point clouds" were generated using `src/paper/generate_point_cloud_figure.py`.

You can also export the predicted Gaussians using the functions in `src/model/ply_export.py`. We never used this for anything though, so for the exported Gaussians to be completely correct, you would have to apply the camera-to-world transformation's rotation to the rotations [here](https://github.com/dcharatan/pixelsplat/blob/a0050e1e052bb0eb5dab06c2bbd6be2c4bfc6225/src/model/encoder/common/gaussian_adapter.py#L94). Right now, the camera-to-world rotation is only applied to the precomputed covariances that the rest of the code (including `generate_point_cloud_figure.py`) uses.

**Comment by thucz** [comment]
Thanks for your reply!

**Comment by kam1107** [comment]
Hi! I was also trying to visualize gaussians. If I export gaussians in test_step, the the c2w rotation is already applied right (since it goes through GuassianAadapter in EncoderEpipolar)?
![image](https://github.com/dcharatan/pixelsplat/assets/13587147/f505c133-97e0-4f13-9354-659cc928acb0)
