### ISSUE TITLE
Context distance when training models of 3-views version

### ISSUE THREAD

**Issue by yifliu3** [dcharatan/pixelsplat#90]
Dear devs,

Thanks a lot for your contribution. I would like to kindly ask how the min and max context distances are set when training the 3-view version of the model. Thank you very much for your help!

**Comment by dcharatan** [comment]
Two context views are chosen normally, and a third is then chosen randomly between them. See here:

https://github.com/dcharatan/pixelsplat/blob/5d5735eaeea59b67eb9527192bcde3aa20da0342/src/dataset/view_sampler/view_sampler_bounded.py#L109-L121
