### ISSUE TITLE
Max gap in Bounded View Sampler

### ISSUE THREAD

**Issue by BannyStone** [dcharatan/pixelsplat#93]
Hi authors,

Congratulations on the amazing work!

I have a question regarding this line of code in the view_sampler_bounded.py
https://github.com/dcharatan/pixelsplat/blob/5d5735eaeea59b67eb9527192bcde3aa20da0342/src/dataset/view_sampler/view_sampler_bounded.py#L61

However, max_gap = min(num_views - 1, **max_gap**) makes more sense to me because the max_gap should be bounded by the number of views. Looking forward to any insights.

Thanks,
Lei

**Comment by dcharatan** [comment]
Thanks for pointing this out! This was previously pointed out [here](https://github.com/dcharatan/pixelsplat/issues/34) and fixed [here](https://github.com/dcharatan/pixelsplat/commit/282c39ffb2829ab2f4b22c309a072c2025628a83), but then I managed to merge in the broken version [here](https://github.com/dcharatan/pixelsplat/commit/7b8f50372b776e9bfc9520f0f63b2fce872ff07a) when I added the code from the CVPR rebuttal (whoops). I've made a [change to fix this again](https://github.com/dcharatan/pixelsplat/commit/dea327d24820b59c5293677fc1f5e6557617430d).
