### ISSUE TITLE
KeyError: 'SLURM_NODEID'

### ISSUE THREAD

**Issue by oyangavi** [dcharatan/pixelsplat#99]
When I tried to train or evaluate, I encountered this problem. 
![19861728453716_ pic](https://github.com/user-attachments/assets/67a2b51a-4951-48ce-a4b3-87c1ae7d88b4)

Also, I am a little confused about the unziped re10k_subset,
![image](https://github.com/user-attachments/assets/a8f8cab8-2bed-451a-bb8c-183fc0da3138)

should not these be picture formats?

Thanks in advance

**Comment by oyangavi** [comment]
Solved, deleted all slurm related codes

**Comment by xiaobaitu123321** [comment]
Could you tell me where you deleted all the codes related to SLURM? I'm also encountering the same problem. I'm looking forward to your help.

**Comment by zhangchenqi123** [comment]
`plugins=[SLURMEnvironment(auto_requeue=False)],`
delete this line in main.py
